Shopify/checkout-sheet-kit-react-native

- CHANGELOG.md
- modules/@shopify/checkout-sheet-kit/RNShopifyCheckoutSheetKit.podspec
- modules/@shopify/checkout-sheet-kit/android/gradle.properties
- modules/@shopify/checkout-sheet-kit/package.json
- sample/android/gradle.properties
- sample/ios/Podfile.lock
- sample/ios/ReactNative.xcodeproj/project.pbxproj
> 1.0.0 - General Availability

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
---
> [!IMPORTANT]
>
> - [x] I've updated any documentation related to these changes.
---
<details>
</details>
> [!TIP] 
> See the [Contributing documentation](./CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the library.
> Improve contribution guidelines + PR template

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/ci.yml
- modules/@shopify/checkout-sheet-kit/package.json
> Improve issue template

- .github/workflows/publish.yml
Update dist tags for latest and beta
> Update dist tags

- .github/pull_request_template.md
Replace relative with absolute links in pr template to ensure they resolve correclty.
n/a
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releas …
> replace relative with absolute links

- .github/workflows/stale.yml
Remove duplicate key in workflow. 
Use stale label for PRs and issues
N.B. my IDE did some autoformatting, probably best to hide whitespace when reviewing
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing …
> Remove duplicate key in stale workflow

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Add a feature request template to the repo
n/a
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on …
> Add feature request template

- CHANGELOG.md
- modules/@shopify/checkout-sheet-kit/RNShopifyCheckoutSheetKit.podspec
- modules/@shopify/checkout-sheet-kit/android/gradle.properties
- modules/@shopify/checkout-sheet-kit/package.json
- sample/android/gradle.properties
- sample/ios/Podfile.lock
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new version of the library.
> Upgrade dependencies

- CHANGELOG.md
- README.md
- modules/@shopify/checkout-sheet-kit/RNShopifyCheckoutSheetKit.podspec
- modules/@shopify/checkout-sheet-kit/android/gradle.properties
- modules/@shopify/checkout-sheet-kit/package.json
- modules/@shopify/checkout-sheet-kit/src/pixels.d.ts
- sample/android/gradle.properties
- sample/ios/Podfile.lock
CLOSES https://github.com/Shopify/checkout-sheet-kit-react-native/issues/109
Update android and swift dependencies
Update pixel types to reflect latest checkout schema
Complete checkout, check the checkout_completed event is populated as expected.
Adding a discount code, phone number, etc will help in ensuring it's complete
> [!IMPORTANT]
>
> - [ ] I've updated the [README](https://github.com/shopify/checkout-sheet-kit-react-na …
> Update web pixel schema

- CHANGELOG.md
- modules/@shopify/checkout-sheet-kit/package.json
Releasing `3.0.4`
Includes:
- #127
- #126 
- #125 
- #123 
- #121 
- #120 
- #119 
- #118 
- #116 
- #115 
- #114
> PATCH - 3.0.4

- .gitignore
- sample/android/app/build.gradle
- sample/package.json
- sample/scripts/release_android
- sample/src/App.tsx
Improves the `yarn sample release:android` command, with notes on how to test the release build.
> Improve "release:android" command

- .vscode/extensions.json
> Add vscode recommendations

- README.md
Update readme to reflect Checkout Kit rename
> Update README.md for Checkout Kit Rename

- modules/@shopify/checkout-sheet-kit/tests/context.test.tsx
- modules/@shopify/checkout-sheet-kit/tests/index.test.ts
- modules/@shopify/checkout-sheet-kit/tests/linking.test.ts
File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------|---------|----------|---------|---------|-------------------
All files    |   74.16 |    80.39 |   65.85 |   74.78 |
context.tsx |    6.89 |        0 |       0 |    7.14 | 56-150
errors.d.ts |     100 |      100 |     100 |     100 |
index.ts    |   94.36 |    90.24 |   95.45 |   94.36 | 63,110,348-355
File         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------|---------|----------|---------|---------|-------------------
All files    |     100 |    98.03 |     100 |     100 |
context.tsx |     100 |      100 |     100 |     100 |
errors.d.ts |     100 |      100 |     100 |     100 |
index.ts    |     100 |    97.56 |     100 |     100 | 229
---
> [!IMPORTANT]
>
> - [x] I've …
> Improve test coverage

- __mocks__/react-native.ts
- jest.config.js
- jest.setup.ts
- modules/@shopify/checkout-sheet-kit/tests/context.test.tsx
- modules/@shopify/checkout-sheet-kit/tests/index.test.ts
Leverages a `__mocks__` directory for common react-native mocks.
---
> [!IMPORTANT]
>
> - [x] I've added tests to support my implementation
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) …
> Move common mocks to __mocks__ directory

- .github/workflows/ci.yml
- sample/android/build.gradle
- sample/android/gradle.properties
Configure Android memory
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a new …
> Configure Android memory

- .github/workflows/ci.yml
- sample/scripts/test_android
Increase Android heap memory
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to publish a …
> Increase Android heap memory

- .github/dependabot.yaml
Configure dependabot to ignore major upgrades
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on …
> Configure dependabot to ignore major upgrades

- package.json
- yarn.lock
Upgrades jest to latest
---
> [!IMPORTANT]
>
>
> _Releasing a new version of the kit?_
>
> - [ ] I have bumped the version number in the [`package.json` file](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/package.json#L4).
> - [ ] I have added a …
> Upgrade jest to latest

- .github/dependabot.yaml
Updates dependabot configuration
---
> [!IMPORTANT]
>
>
> _Releasing a new version of the kit?_
>
> - [ ] I have bumped the version number in the [`package.json` file](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/package.json#L4).
> - [ ] I have added a …
> Update dependabot configuration

- .github/actions/setup-simulator/action.yml
- .github/workflows/ci.yml
- modules/@shopify/checkout-sheet-kit/ios/AcceleratedCheckoutButtons+Extensions.swift
- modules/@shopify/checkout-sheet-kit/ios/AcceleratedCheckoutButtons.swift
- sample/ios/ReactNative.xcodeproj/project.pbxproj
- sample/ios/ReactNativeTests/AcceleratedCheckouts_SupportedTests.swift
- sample/ios/ReactNativeTests/AcceleratedCheckouts_UnsupportedTests.swift
- sample/scripts/test_ios
Adds Swift tests for Accelerated Checkouts
---
> [!IMPORTANT]
>
> - [x] I've added tests to support my implementation
>
> _Releasing a new version of the kit?_
>
> - [ ] I have bumped the version number in the [`package.json` file](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/package.json#L4).
> - [ ] I have added a …
> Accelerated Checkouts Tests

- CHANGELOG.md
- modules/@shopify/checkout-sheet-kit/RNShopifyCheckoutSheetKit.podspec
- modules/@shopify/checkout-sheet-kit/ios/AcceleratedCheckoutButtons.swift
- modules/@shopify/checkout-sheet-kit/ios/ShopifyCheckoutSheetKit+EventSerialization.swift
- modules/@shopify/checkout-sheet-kit/ios/ShopifyCheckoutSheetKit.swift
- modules/@shopify/checkout-sheet-kit/src/components/AcceleratedCheckoutButtons.tsx
- modules/@shopify/checkout-sheet-kit/tests/AcceleratedCheckoutButtons.test.tsx
- sample/Gemfile.lock
- sample/ios/Podfile.lock
- sample/ios/ReactNative.xcodeproj/project.pbxproj
- sample/ios/ReactNativeTests/AcceleratedCheckouts_SupportedTests.swift
- sample/ios/ReactNativeTests/EventSerializationTests.swift
The main changes:
- Switch statements for wallets become `Wallet(rawValue: walletString)`
- Switch statements for `RequiredContactFields` become `RequiredContactField(rawValue: walletString)`
- Removes `unknown` render state, replaces with `error`
- Appends `reason` to error render state
- Derives the wallets from the instance, rather than a static array in the library
TODO: Add tests after rebasing on #289  
---
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of Conduct](https://github.com/shopify/checkout-sheet-kit-react-native/blob/main/.github/CODE_OF_CONDUCT.md …
> Integrate Swift RC 6

- modules/@shopify/checkout-sheet-kit/RNShopifyCheckoutSheetKit.podspec
- modules/@shopify/checkout-sheet-kit/android/gradle.properties
- modules/@shopify/checkout-sheet-kit/package.json
- sample/android/gradle.properties
- sample/ios/Podfile.lock
Updates underlying dependencies to latest stable.
---
> [!IMPORTANT]
>
> - [x] I've added tests to support my implementation
> - [x] I've updated the [README](https://github.com/shopify/checkout-sheet-kit-react-native).
>
> _Releasing a new version of the kit?_
>
> - [x] I have bumped the version number in the [`package.json` file](https://github.com/Shopify/checkout-sheet-kit-react-native/blob/main/modules/%40shopify/checkout-sheet-kit/package.json#L4).
---
> [!TIP]
> See the …
> [Stable 3.4.0] Swift 3.4.0, Android 3.5.3
